baseURL = 'https://kurian-thomas.github.io/'
languageCode = 'en-us'
title = "Nova's Blog"

[markup]
  [markup.highlight]
    lineNos = true
    style = "dracula" 
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
